version: '3.6'

services:
  master:
    image: unguiculus/jenkins-master-@JENKINS_VERSION@:@MASTER_BUILD_NUMBER@
    build:
      context: ./master
    container_name: jenkins-master
    labels:
      - "traefik.frontend.rule=Host:jenkins.unguiculus.io"
      - "traefik.backend=master"
      - "traefik.backend.loadbalancer=wrr"
      - "traefik.docker.network=ci-net"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.default.protocol=http"
    networks:
      - ci-net
    volumes:
      - data_master:/var/jenkins_home
      - ./data/bootstrap:/etc/jenkins_bootstrap
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "30"

  agent:
    image: unguiculus/jenkins-agent:@AGENT_IMAGE_VERSION@
    build:
      context: ./agent
    container_name: jenkins-agent
    networks:
      - ci-net
    depends_on:
      - master
    restart: unless-stopped
    volumes:
      - data_agent:/home/jenkins/workspace
      - $HOME/.gitconfig:/home/jenkins/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "10m"
        max-file: "30"

volumes:
  data_master:
  data_agent:

networks:
  ci-net:
    external: true
