---
- hosts: jenkins
  become: True
  become_method: sudo
  gather_facts: True

  roles:
    - role: basic_stuff
      tags:
        - basic

    - role: angstwad.docker_ubuntu
      docker_group_members:
        - ubuntu
      tags:
        - docker

    - role: docker_config
      tags:
        - config

    - role: docker_service
      tags:
        - service
